name: Trigger auto deployment for simontestconapp2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '"./1.22/Dockerfile.c9s"/**'
    - '.github/workflows/simontestconapp2-AutoDeployTrigger-c43ad1f8-805f-41ed-8dd2-28b3a2ab724c.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: simontestcr.azurecr.io
          username: ${{ secrets.SIMONTESTCONAPP2_REGISTRY_USERNAME }}
          password: ${{ secrets.SIMONTESTCONAPP2_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: simontestcr.azurecr.io/simontestconapp2:${{ github.sha }}
          file: "./1.22/Dockerfile.c9s"/Dockerfile
          context: "./1.22/Dockerfile.c9s"/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SIMONTESTCONAPP2_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n simontestconapp2 -g SimonTestConApp --server simontestcr.azurecr.io --username  ${{ secrets.SIMONTESTCONAPP2_REGISTRY_USERNAME }} --password ${{ secrets.SIMONTESTCONAPP2_REGISTRY_PASSWORD }}
            az containerapp update -n simontestconapp2 -g SimonTestConApp --image simontestcr.azurecr.io/simontestconapp2:${{ github.sha }}
